//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFStudentServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmet
    {
        public string OznakaPredmeta { get; set; }
        public string NazivPredmeta { get; set; }
        public short BrESPBbodova { get; set; }
    }
}
