//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFStudentServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int UserID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string BrojIndeksa { get; set; }
        public string JMBG { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string LoginErrorMessage { get; internal set; }
    }
}
